name: â˜ï¸Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ðŸ³Docker]
    types:
        - completed


jobs:
  Notify:
    name: Discord
    runs-on: ubuntu-latest
    steps:
      - name: Actions Start Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New Docker Ready"
          noprefix: true
          color: 0xf5d442
      # - name: Actions Start Apprise
      #   uses: cstuder/apprise-ga@v3
      #   with:
      #     title: "Notication title"
      #     message: "Message"
      #   env:
      #     APPRISE_URL: ${{ secrets.APPRISE_URL }}
      # - name: send telegram message on push
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: |
      #       ${{ github.actor }} created commit:
      #       Commit message: ${{ github.event.commits[0].message }}
            
      #       Repository: ${{ github.repository }}
            
      #       See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}


      # - name: get repository name
      #   run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      # - name: update repo category by language
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REPOSITORY: ${{ env.REPOSITORY_NAME }}
      #     USERNAME: ${{ github.repository_owner }}

  # Koyeb:
  #   - name: Build and deploy the application to Koyeb
  #     uses: koyeb/action-git-deploy@v1
  #     with:
  #       app-name: my-koyeb-app
  #       service-name: my-koyeb-service
  #       service-env: "PORT=8080"
  #       service-ports: "8080:http"
  #       service-routes: "/health:8080"



  # Deta:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3.5.2
  #     - name: Deploy to Deta
  #       uses: BogDAAAMN/deta-deploy-action@v1.0.1
  #       with:
  #         deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
  #         deta-name: ${{ secrets.DETA_STAGING_MICRO_NAME }}
  #         deta-project: ${{ secrets.DETA_PROJECT_NAME }}