[default]
#üìùtokenlist
TOKEN_MAINNET_LIST = 'https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json'
TOKEN_TESTNET_LIST = 'https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json'
TOKEN_PERSONAL_LIST = 'https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json'


[testing]
LOGLEVEL = 'DEBUG'
HOST = "0.0.0.0"
PORT = 8080

CHAIN_ID = '10'
WALLET_ADDRESS = ''
PRIVATE_KEY = ''

BLOCK_EXPLORER_API = ''

APOLLO_SPOT_API_KEY = ''
APOLLO_SPOT_API_SECRET = ''

APOLLO_FUTURE_API_KEY = ''
APOLLO_FUTURE_API_SECRET = ''