########################################
###          DEFAULT SETTINGS        ###
########################################

# Any of those settings can be changed
# by the user. To overwrite a setting, 
# create a settings.toml or load the 
# settings from .env file or vars.
# As an example, to disable the 
# dxsp object:
# settings.toml
# [default]
# dxsp_enabled = false
[default]
# Dynaconf settings verification
VALUE = "On default"
# Talky App Related Settings
# Enable/Disable DXSP
dxsp_enabled = true

# help message used in talky app
dxsp_commands = """
üéØ BUY WBTC
üéØ /q WBTC
üè¶ /bal
üè¶ /pos
"""
# Header to use for retrieving urls content below
headers = {User-Agent= 'Mozilla/5.0'}

# DEX ABI to use in case you have no explorer setup
dex_router_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v2/router02.abi"
# DEX factory address to use
dex_factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
# DEX ABI to use in case you have no explorer setup
dex_erc20_abi_url = "https://raw.githubusercontent.com/Uniswap/interface/44c355c7f0f8ab5bdb3e0790560e84e59f5666f7/src/abis/erc20.json"

# token list using uniswap tokenlist format
# https://github.com/mraniki/tokenlist
# this can be used to avoid using coingecko
# or be used for niche token not listed anywhere
# or for testnet
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"


[default.dex.eth]
wallet_address = "0x1234567890123456789012345678901234567890"
private_key = "0xdeadbeef45ab87712ad64ccb3b10217737f7faacbf2872e88fdd9a537d8fe266"
rpc = "https://rpc.ankr.com/eth"
protocol_type = "uniswap"
protocol_version = 2
api_endpoint = ''
api_key = ""
router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
trading_asset_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
trading_risk_amount = 10
trading_slippage = 2
block_explorer_url = "https://api.etherscan.io/api?"
block_explorer_api = "798437294880920392"

[default.dex.bsc]
wallet_address = "0x1234567890123456789012345678901234567890"
private_key = "0xdeadbeef45ab87712ad64ccb3b10217737f7faacbf2872e88fdd9a537d8fe266"
rpc = "https://rpc.ankr.com/bsc"
protocol_type = "uniswap"
protocol_version = 2
api_endpoint = ''
api_key = ""
router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
factory_contract_addr = "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
trading_asset_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
trading_risk_amount = 10
trading_slippage = 2
block_explorer_url = "https://api.bscscan.com/api?"
block_explorer_api = "798437294880920392"

[default.dex.polygon]
wallet_address = "0x1234567890123456789012345678901234567890"
private_key = "0xdeadbeef45ab87712ad64ccb3b10217737f7faacbf2872e88fdd9a537d8fe266"
rpc = "https://rpc.ankr.com/polygon"
protocol_type = "0x"
protocol_version = 4
api_endpoint = "https://polygon.api.0x.org/"
api_key = ""
router_contract_addr = "0xdef1c0ded9bec7f1a1670819833240f027b25eff"
factory_contract_addr = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
trading_asset_address = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
trading_risk_amount = 10
trading_slippage = 2
block_explorer_url = "https://api.polygonscan.com/api?"
block_explorer_api = "798437294880920392"


########################################
###     END OF DEFAULT SETTINGS      ###
########################################