[default]
loglevel = "INFO"
headers = {User-Agent= 'Mozilla/5.0'}
#üìùtokenlist
token_mainnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/all.json"
token_testnet_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/testnet.json"
token_personal_list = "https://raw.githubusercontent.com/mraniki/tokenlist/main/TT.json"
#üìùtrading setup
trading_asset = "USDT"
trading_risk_amount = 10 # 10% of the position
dex_trading_slippage = 2 # 2 % slippage
#user settings
dex_wallet_address = "0x1234567890123456789012345678901234567890" #this is an example
dex_private_key = "0xdeadbeef" #this is an example
#chain_1 #see below for other chain ids or use https://chainlist.org to overwrite settings
dex_chain_id = 1
dex_protocol_type = "uniswap_v2" #0x | 1inch | uniswap_v3
dex_rpc = "https://rpc.ankr.com/eth"
dex_block_explorer_url = "https://api.etherscan.io/api?"
dex_block_explorer_api =  "798437294880920392"  #this is an example
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D" #UNI_V2
dex_router_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v2/router02.abi"
dex_erc20_abi_url = "https://raw.githubusercontent.com/Uniswap/interface/44c355c7f0f8ab5bdb3e0790560e84e59f5666f7/src/abis/erc20.json"
# dex_router_contract_addr = "0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45" #UNI_V3
dex_quoter_contract_addr = "0x61fFE014bA17989E743c5F6cB21bF9697530B21e" #UNI_V3_QUOTERV2
dex_quoter_abi_url = "https://raw.githubusercontent.com/uniswap-python/uniswap-python/master/uniswap/assets/uniswap-v3/quoter.abi"
#protocol specific
#ü¶Ñ1inch
dex_1inch_url = "https://api.1inch.exchange/v5.0/"
dex_1inch_limit_url = "https://limit-orders.1inch.io/v3.0/"
#0Ô∏è‚É£0x
dex_0x_url = "https://api.0x.org/mainnet"
dex_0x_api_key = "" 
#ü™êapollo
dex_apollo_url = "https://fapi.apollox.finance/"
dex_apollo_spot_api_key = ""
dex_apollo_spot_api_secret = ""
dex_apollo_future_api_key = ""
dex_apollo_future_api_secret = ""

[chain_1]
dex_chain_id = 1
dex_rpc = "https://rpc.ankr.com/eth"
dex_block_explorer_url = "https://api.etherscan.io/api?"
dex_protocol_type = "uniswap_v2"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
dex_0x_url = "https://api.0x.org/mainnet/"

[chain_5]
loglevel = "DEBUG"
dex_chain_id = 5
dex_rpc = "https://rpc.ankr.com/eth_goerli"
dex_block_explorer_url = "https://api-Goerli.etherscan.io/api?"
dex_protocol_type = "uniswap_v2"
dex_router_contract_addr = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
dex_0x_url = "https://goerli.api.0x.org/"

[chain_11155111]
loglevel = "DEBUG"
dex_chain_id = 11155111
dex_rpc = "https://rpc.ankr.com/eth_sepolia"
dex_block_explorer_url = "https://api-Sepolia.etherscan.io/api?"
dex_protocol_type = "0x"
dex_router_contract_addr = "0x1f98431c8ad98523631ae4a59f267346ea31f984"
dex_0x_url = "https://sepolia.api.0x.org/"

[chain_56]
dex_chain_id = 56
dex_rpc = "https://rpc.ankr.com/bsc"
dex_block_explorer_url = "https://api.bscscan.com/api?"
dex_block_explorer_api =  ""
dex_protocol_type = "uniswap_v2"
dex_router_contract_addr = "0x10ED43C718714eb63d5aA57B78B54704E256024E" #pancakeswap V2
dex_0x_url = "https://bsc.api.0x.org/"

[chain_97]
loglevel = "DEBUG"
dex_chain_id = 97
dex_rpc = "https://rpc.ankr.com/bsc_testnet_chapel"
dex_block_explorer_url = "https://api-testnet.bscscan.com/api?"
dex_router_contract_addr = ""

[chain_42161]
loglevel = "DEBUG"
dex_chain_id = 42161
dex_rpc = "https://rpc.ankr.com/arbitrum"
dex_block_explorer_url = "https://api-testnet.bscscan.com/api?"
dex_router_contract_addr = "0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f"
dex_0x_url = "https://arbitrum.api.0x.org/"