name: ğŸ‘·Flow

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  merge_group:


jobs:
  # secret:
  #   uses: mraniki/coding_toolset/.github/workflows/ğŸ‘ï¸Secret.yml@main
  #   with:
  #     repo: ${{ github.event.repository.name }}
  #   secrets: inherit
  lint:
    uses: mraniki/coding_toolset/.github/workflows/ğŸ¦ºLint.yml@main
    secrets: inherit
  test:
    #needs: [lint,secret]
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/ğŸ§ªTest.yml@main
    # with:
    #   settings_location: ${{ needs.secret.outputs.SETTINGS_LOCATION }}
    secrets: inherit
  build:
    needs: [lint]
    uses: mraniki/coding_toolset/.github/workflows/ğŸBuild.yml@main
    # with:
    #   settings_token: ${{ needs.secret.outputs.TOKEN }} 
    secrets: inherit
  release:
    needs: [build]
    uses: mraniki/coding_toolset/.github/workflows/ğŸ“¦Release.yml@main
    with:
      settings_publish: true
    # with:
    #   settings_pypi: ${{ needs.secret.outputs.PYPI_API_TOKEN }}
    #   settings_token: ${{ needs.secret.outputs.TOKEN }} 
    secrets: inherit
